on: 
  push: 
    branches: [ "main" ] 

jobs: 
  build_and_test: 
    runs-on: ubuntu-latest 
    steps:
      - name: repo auschecken
        uses: actions/checkout@v4
    
      - name: Docker installieren
        run: |
          docker --version
    
      - name: Docker Image bauen
        run: |
          docker build -t oldschool-ci-demo-jeanette_lossau .
      
      - name: Container starten
        run: | 
          output=$(docker run oldschool-ci-demo-jeanette_lossau) 
          echo "$output" 
          if [ "$output" != "OldSchool GmbH –  automatischer Build erfolgreich! (jeanette l.)" ]; then 
            echo "❌ Test fehlgeschlagen!" 
            exit 1 
          fi 
    
      - name: Ausgabe testen
        run: |
          echo "Test yay"
