on: 
  push: 
    branches: [ "main" ] 
  pull_request:
    branches: ["main"]

jobs: 
  build_and_test: 
    runs-on: ubuntu-latest 
    steps:
      - name: repo auschecken
        uses: actions/checkout@v4

     #Installierung bringt es zum absturz
     #weil ubuntu-latest docker schon installiert hat
      - name: Docker installieren
        run: |
          docker --version
    
      - name: Docker Image bauen
        run: |
          docker build -t oldschool-ci-demo-jeanettelossau .
      
      - name: Container starten
        run: | 
          output=$(docker run oldschool-ci-demo-jeanettelossau) 
          echo "Output=§output" >> $GITHUB_ENV
     
      - name: Container Testen
        run: |
          if [ "$Output" != "OldSchool GmbH - automatischer Build erfolgreich! (Jeanette L.)" ]; then 
            echo "❌ Test fehlgeschlagen!" 
            exit 1 
          fi 
          
